export const AGREE_AND_CREATE_ACCOUNT = "AGREE_AND_CREATE_ACCOUNT";
export const AGREE_AND_CREATE_ACCOUNT_SUCCESS = "AGREE_AND_CREATE_ACCOUNT_SUCCESS";
export const AGREE_AND_CREATE_ACCOUNT_ERROR = "AGREE_AND_CREATE_ACCOUNT_ERROR";
export const ADD_PERSONAL_DATA_TO_ACCOUNT = "ADD_PERSONAL_DATA_TO_ACCOUNT";
export const RESET_STATE = "RESET_STATE";
